export const tablaCriticosTajo = [
  { min: -49, max: 5, texto: "Un golpe débil que no produce daño extra." },
  { min: 6, max: 20, texto: "Herida leve en la pantorrilla. 1 Punto de Vida por asalto." },
  { min: 21, max: 35, texto: "Golpe en la parte superior de la pierna. -5 PV si no se llevan grebas, 3 PV y 4-2 PV por asalto." },
  { min: 36, max: 50, texto: "Herida leve en el pecho. -3 PV. 1 PV por asalto. -5 a la actividad." },
  { min: 51, max: 65, texto: "Herida leve en el antebrazo. -4 PV. 2 PV más por asalto. Aturdido durante 1 asalto." },
  { min: 66, max: 79, texto: "Herida menos grave en el muslo. -6 PV. 1 PV por asalto. -10 a la actividad. Aturdido durante 2 asaltos." },
  { min: 80, max: 86, texto: "Un golpe en el cuello secciona la arteria carótida. Cuello roto. Muerte instantánea o 1 asalto de intensa agonía." },
  { min: 87, max: 89, texto: "Tajo en los músculos y tendones del brazo que esgrime el arma. El brazo queda inutilizado. -10 PV y 1 PV más cada asalto." },
  { min: 90, max: 94, texto: "Un ojo destruido. -10 PV. Aturdido durante 30 asaltos." },
  { min: 95, max: 99, texto: "Destripado, muerte instantáneamente. 25% de que el arma se quede atascada en el contrincante durante 2 asaltos." },
  { min: 100, max: 110, texto: "Inconsciente 6 horas debido a un tajo en el lado de la cabeza. -15 PV. Si no lleva yelmo, muerte instantánea." },
  { min: 111, max: 116, texto: "Mano cercenada. 12 Puntos de Vida por asalto. Cae al suelo y queda aturdido durante 6 asaltos." },
  { min: 117, max: 119, texto: "Tajo en la espina dorsal. Colapso inmediato. Paralizado desde el cuello para abajo, permanentemente. -20 PV adicionales." },
  { min: 120, max: 120, texto: "Un tajo en la cabeza destruye el cerebro, lo que hace difícil que el pobre infeliz siga con vida. Cae fulminado." },
];

export const tablaCriticosAplastamiento = [
  { min: -49, max: 5, texto: "Poco dominio. No hay daño extra. +0." },
  { min: 6, max: 20, texto: "Fractura leve en las costillas. -5 PV. -5 a la actividad." },
  { min: 21, max: 35, texto: "Golpe en un costado. -4 PV. -40 a la actividad durante 1 asalto." },
  { min: 36, max: 50, texto: "Golpe en el antebrazo. -5 PV. Aturdido durante 1 asalto." },
  { min: 51, max: 65, texto: "Golpe al hombro rompe el escudo o el hueso. Brazo inutilizado." },
  { min: 66, max: 79, texto: "Hueso de la pierna roto. -12 PV. -40 actividad. Aturdido 2 asaltos." },
  { min: 80, max: 86, texto: "Golpe en la frente. -30 PV. Ojo destruido. Coma 1 mes si lleva yelmo." },
  { min: 87, max: 89, texto: "Brazo del arma roto. Brazo inutilizado. -8 PV. Aturdido 2 asaltos." },
  { min: 90, max: 94, texto: "Rodilla destruida. -9 PV. -60 a actividad. Derribado. Aturdido 3 asaltos." },
  { min: 95, max: 99, texto: "Golpe en base del cuello. Parálisis de hombros para abajo. -25 PV." },
  { min: 100, max: 110, texto: "Golpe en la cabeza. Inconsciente 4h. Si no hay yelmo, cráneo aplastado. -20 PV." },
  { min: 111, max: 116, texto: "Codo destrozado. Brazo inutilizado. Aturdido 5 asaltos." },
  { min: 117, max: 119, texto: "Golpe en costado. Tórax aplastado. Muerte en 3 asaltos." },
  { min: 120, max: 120, texto: "Golpe en el pecho. Corazón destruido. Muerte instantánea. -25 PV." },
];

export const tablaCriticosPerforacion = [
  { min: -49, max: 5, texto: "Un golpe torpe que no produce daño extra." },
  { min: 6, max: 20, texto: "Pinchazo leve en el muslo. -3 PV. Aturdido 1 asalto." },
  { min: 21, max: 35, texto: "Herida penetrante en el brazo. -5 PV. 1 PV por asalto. Aturdido 1 asalto." },
  { min: 36, max: 50, texto: "Golpe entre costillas. -6 PV. 2 PV por asalto. -10 a la actividad." },
  { min: 51, max: 65, texto: "Estocada en el pecho. -8 PV. 3 PV por asalto. Aturdido 2 asaltos." },
  { min: 66, max: 79, texto: "Herida profunda en el abdomen. -10 PV. 5 PV por asalto. Aturdido 3 asaltos." },
  { min: 80, max: 86, texto: "Golpe entre costillas perfora el pulmón. -12 PV. 6 PV por asalto. Derribado." },
  { min: 87, max: 89, texto: "Estocada en el muslo. Hueso dañado. Movimiento reducido. -10 PV." },
  { min: 90, max: 94, texto: "Estocada en el cuello. Arteria dañada. Muerte en 5 asaltos." },
  { min: 95, max: 99, texto: "Golpe directo al corazón. Muerte en 1 asalto. -25 PV. Arma clavada." },
  { min: 100, max: 110, texto: "Golpe en el ojo. Ceguera permanente. -15 PV. Aturdido 10 asaltos." },
  { min: 111, max: 116, texto: "Herida en columna. Parálisis parcial. -20 PV. Derribado y aturdido." },
  { min: 117, max: 119, texto: "Estocada atraviesa cráneo. Muerte en segundos. -30 PV." },
  { min: 120, max: 120, texto: "La hoja atraviesa el corazón y sale por la espalda. Muerte instantánea." },
];

export const tablaCriticosDesequilibrio = [
  { min: -49, max: 5, texto: "Fallo total. El atacante pierde el equilibrio." },
  { min: 6, max: 20, texto: "El objetivo pierde el equilibrio. -10 a su próxima acción." },
  { min: 21, max: 35, texto: "Tropiezo leve. -20 a la actividad por 1 asalto." },
  { min: 36, max: 50, texto: "Desequilibrio notable. Derribado. Pierde su próxima acción." },
  { min: 51, max: 65, texto: "Empujón fuerte. El objetivo cae al suelo y suelta lo que tenía en manos." },
  { min: 66, max: 79, texto: "El objetivo choca contra otro obstáculo. Pierde 2 asaltos. Derribado." },
  { min: 80, max: 86, texto: "Caída aparatosa. Aturdido 2 asaltos. -40 a la actividad." },
  { min: 87, max: 89, texto: "Resbala y se golpea. -5 PV. Pierde su próximo turno." },
  { min: 90, max: 94, texto: "Derribado violentamente. Aturdido 3 asaltos. Pierde su acción." },
  { min: 95, max: 99, texto: "Vuela por los aires. Aturdido 5 asaltos. Recibe daño adicional." },
  { min: 100, max: 110, texto: "Lanza su arma al caer. Aturdido 6 asaltos. -15 PV." },
  { min: 111, max: 116, texto: "Cae de mala forma. Rompe un hueso. -20 PV. Movimiento reducido." },
  { min: 117, max: 119, texto: "Se golpea la cabeza. Inconsciente por 1h. -25 PV." },
  { min: 120, max: 120, texto: "Golpe fatal en la caída. Cuello roto. Muerte instantánea." },
];
